

export const CLEAR_CONFIRMED_LIST = "CLEAR_CONFIRMED_LIST"
export const CLEAR_DEATH_LIST = "CLEAR_DEATH_LIST"
export const CLEAR_RECOVERED_LIST = "CLEAR_RECOVERED_LIST"

export const FETCH_CONFIRMED_TOTAL = "FETCH_CONFIRMED_TOTAL"
export const FETCH_DEATH_TOTAL = "FETCH_DEATH_TOTAL"
export const FETCH_RECOVERED_TOTAL = "FETCH_RECOVERED_TOTAL"

export const FETCH_CONFIRMED_LIST = "FETCH_CONFIRMED_LIST"
export const FETCH_DEATH_LIST = "FETCH_DEATH_COUNTRY_LIST"
export const FETCH_RECOVERED_LIST = "FETCH_RECOVERED_COUNTRY_LIST"

export const FETCH_LAST_UPDATEED_TIME = "FETCH_LAST_UPDATEED_TIME"
export const SET_CHART_DATA = "SET_CHART_DATA"


export const CovidStatus = {
  Confirmed: "confirmed",
  Recovered: "recovered",
  Deaths: "deaths",
};